services:
  - type: web
    name: discord-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: TOKEN
        value: YOUR_DISCORD_BOT_TOKEN
